"""initial schema with source-agnostic LV/Position fields

Revision ID: 8c5f47b64684
Revises:
Create Date: 2026-07-23 07:39:27.129089
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c5f47b64684"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lv",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.String(length=256), nullable=False),
        sa.Column("project_name", sa.String(length=512), nullable=True),
        sa.Column("client", sa.String(length=512), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("GAEB", "MANUAL", "EXCEL", name="sourcetype"),
            nullable=False,
        ),
        sa.Column(
            "source_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_table(
        "lot",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lv_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=512), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lv_id"],
            ["lv.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lv_id", "number", name="uq_lot_lv_number"),
    )
    op.create_table(
        "section",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lot_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("number", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=512), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["lot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["section.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lot_id", "number", name="uq_section_lot_number"),
    )
    op.create_table(
        "position",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lv_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("oz", sa.String(length=64), nullable=False),
        sa.Column("short_text", sa.Text(), nullable=False),
        sa.Column("long_text", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=15, scale=5), nullable=True),
        sa.Column(
            "position_type",
            sa.Enum(
                "NORMAL", "ALTERNATIV", "BEDARF", "ZULAGENPOSITION", name="positiontype"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "REVIEW",
                "DONE",
                "BLOCKED",
                name="positionstatus",
            ),
            nullable=False,
        ),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["lv_id"],
            ["lv.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["section.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lv_id", "oz", name="uq_position_lv_oz"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column(
            "old_status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "REVIEW",
                "DONE",
                "BLOCKED",
                name="positionstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "OPEN",
                "IN_PROGRESS",
                "REVIEW",
                "DONE",
                "BLOCKED",
                name="positionstatus",
            ),
            nullable=False,
        ),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "note",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["position.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("note")
    op.drop_table("audit_log")
    op.drop_table("position")
    op.drop_table("section")
    op.drop_table("lot")
    op.drop_table("lv")
    # ### end Alembic commands ###
    sa.Enum(name="positionstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="positiontype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="sourcetype").drop(op.get_bind(), checkfirst=True)
