"""wbs_node as own entity, domain FKs on wbs_node_id

Revision ID: d80224bd0771
Revises: 8c5f47b64684
Create Date: 2026-07-23 11:12:53.987826
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d80224bd0771"
down_revision: str | None = "8c5f47b64684"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wbs_node",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("PROJECT", "LOT", "SECTION", "POSITION", name="wbsnodekind"),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=512), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=256), nullable=False),
        sa.Column("din276_kostengruppe", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["wbs_node.id"], name="fk_wbs_node_parent_id_wbs_node"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "kind", "parent_id", "code", name="uq_wbs_node_parent_code"
        ),
    )
    op.create_index("ix_wbs_node_parent_id", "wbs_node", ["parent_id"], unique=False)
    op.create_index("ix_wbs_node_project_id", "wbs_node", ["project_id"], unique=False)
    op.create_index(
        "uq_wbs_node_root_code",
        "wbs_node",
        ["project_id", "kind", "code"],
        unique=True,
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.add_column("audit_log", sa.Column("wbs_node_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        "fk_audit_log_wbs_node_id_wbs_node",
        "audit_log",
        "wbs_node",
        ["wbs_node_id"],
        ["id"],
    )
    op.add_column("note", sa.Column("wbs_node_id", sa.Uuid(), nullable=False))
    op.drop_constraint(op.f("note_position_id_fkey"), "note", type_="foreignkey")
    op.create_foreign_key(
        "fk_note_wbs_node_id_wbs_node", "note", "wbs_node", ["wbs_node_id"], ["id"]
    )
    op.drop_column("note", "position_id")
    op.add_column("position", sa.Column("wbs_node_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        "fk_position_wbs_node_id_wbs_node",
        "position",
        "wbs_node",
        ["wbs_node_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_position_wbs_node_id_wbs_node", "position", type_="foreignkey"
    )
    op.drop_column("position", "wbs_node_id")
    op.add_column(
        "note",
        sa.Column("position_id", sa.Uuid(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("fk_note_wbs_node_id_wbs_node", "note", type_="foreignkey")
    op.create_foreign_key(
        op.f("note_position_id_fkey"), "note", "position", ["position_id"], ["id"]
    )
    op.drop_column("note", "wbs_node_id")
    op.drop_constraint(
        "fk_audit_log_wbs_node_id_wbs_node", "audit_log", type_="foreignkey"
    )
    op.drop_column("audit_log", "wbs_node_id")
    op.drop_index(
        "uq_wbs_node_root_code",
        table_name="wbs_node",
        postgresql_where=sa.text("parent_id IS NULL"),
    )
    op.drop_index("ix_wbs_node_project_id", table_name="wbs_node")
    op.drop_index("ix_wbs_node_parent_id", table_name="wbs_node")
    op.drop_table("wbs_node")
    # ### end Alembic commands ###
